name: GCC and EMSDK build

on:
    push:
        branches: [main]
        paths-ignore:
            - "website/**"
    pull_request:
        branches: [main]
        paths-ignore:
            - "website/**"

jobs:
    build:
        env:
            EM_VERSION: 3.1.30
            EM_CACHE_FOLDER: "emsdk-cache"

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: "recursive"
                  fetch-depth: 0
            - name: Setup cache
              id: cache-system-libraries
              uses: actions/cache@v3
              with:
                  path: ${{env.EM_CACHE_FOLDER}}
                  key: ${{env.EM_VERSION}}-${{ runner.os }}
            - uses: mymindstorm/setup-emsdk@v12
              with:
                  version: ${{env.EM_VERSION}}
                  actions-cache-folder: ${{env.EM_CACHE_FOLDER}}
            - run: cat $GITHUB_PATH
            - run: yarn
            - run: make
            - run: make test
            - name: update pre-compiled WASM
              run: make update-dist
              if: github.ref == 'refs/heads/main'
            - uses: actions/setup-node@v3
              with:
                  node-version: "18"
            - name: semantic release prep
              run: yarn add -D -W semantic-release semantic-release-monorepo @semantic-release/git
              if: github.ref == 'refs/heads/main'
            - name: semantic release
              run: yarn workspaces run semantic-release -e semantic-release-monorepo 
              if: github.ref == 'refs/heads/main'
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                NPM_TOKEN: ${{ secrets.NPM_TOKEN }}